# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: circuitdojo
      url-base: https://github.com/circuitdojo
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.3.2
      import: true
    - name: board-definitions
      repo-path: nrf9160-feather-board-definitions
      revision: 1.3.x
      path: zephyr/boards/arm/circuitdojo_feather_nrf9160
      remote: circuitdojo
  self:
    # This repository should be cloned to nrf9160-feather
    path: nrf9160-feather