# Import requirements for nRF9160 Feather Examples and Drivers
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.9.1
      import: 
        name-blocklist:
          - matter
          - nrf-802154
          - cjson
          - openthread
          - cmock
          - unity
          - cddl-gen
          - homekit
          - loramac-node
          - lz4
          - lvgl
          - mipi-sys-t
    # Golioth backend
    - name: golioth
      path: modules/lib/golioth
      revision: 5fb65ba35120a2a8da3dd28153a6131daea6e184
      url: https://github.com/golioth/golioth-zephyr-sdk
      import: west-external.yml
    # Pyrinas backend
    - name: pyrinas
      url: https://github.com/pyrinas-iot/pyrinas-zephyr
      revision: v1.7.x
      path: pyrinas
      import: true
    # RTC Driver
    - name: pcf85063a
      url: https://github.com/circuitdojo/pcf85063a
      revision: v1.9.x
      path: pcf85063a
  self:
    # This repository should be cloned to nrf9160-feather
    path: nfed