# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.7.1
      import: true
    # Golioth backend
    - name: golioth
      path: modules/lib/golioth
      revision: main
      url: https://github.com/golioth/zephyr-sdk.git
      import: west-external.yml
    # Pyrinas backend
    - name: pyrinas
      url: https://github.com/pyrinas-iot/pyrinas-zephyr
      revision: v1.7.x
      path: pyrinas
      import: true
    # RTC Driver
    - name: pcf85063a
      url: https://github.com/circuitdojo/pcf85063a
      revision: master
      path: pcf85063a
  self:
    # This repository should be cloned to nrf9160-feather
    path: nfed
