# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v1.6.1
      import: true
    - name: pyrinas
      url: https://github.com/pyrinas-iot/pyrinas-zephyr
      revision: v1.5.x
      path: pyrinas
      import: true
  self:
    # This repository should be cloned to nrf9160-feather
    path: nfed