name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.8
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: nfed

      - name: Set variables
        working-directory: nfed
        id: vars
        run: |
             echo "branch=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
             echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Initialize
        working-directory: nfed
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Tests
        working-directory: nfed
        run: |
          ../zephyr/scripts/twister -W -T tests/

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: nfed_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: nfed/twister-out/